### ISSUE TITLE
Add #CHANGME to all the storageClass fields

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/architecture#26]
https://github.com/openstack-k8s-operators/architecture/blob/d850cf2844f4d443c24049573d18ee314f78c3f6/validated_arch_1/stage4/openstackcontrolplane.yaml#L93

**Comment by gibizer** [comment]
It seems that not just glance but galera also needs a storageClass configuration

**Comment by gibizer** [comment]
> It seems that not just glance but galera also needs a storageClass configuration

No, sorry, it seems only the glance is needed. Actually galera does not delete the pvc when the control plane is deleted, and does not update the storage class in the existing pvc when the control plane is recreated with a new storage class.

**Comment by fultonj** [comment]
The storage class for glance is now kustomizable so this issue should be resolved.

https://github.com/openstack-k8s-operators/architecture/blob/main/lib/control-plane/openstackcontrolplane.yaml#L51
https://github.com/openstack-k8s-operators/architecture/blob/main/examples/va/hci/values.yaml#L201
