### ISSUE TITLE
change examples dir name/move out non-examples out of it

### ISSUE THREAD

**Issue by eshulman2** [openstack-k8s-operators/architecture#66]
It seems like the DT dir was moved into examples and some other configuration which are not examples per say. I think we should move the DT dir and other files out of it/change its name.

**Comment by fultonj** [comment]
The introduction of the examples directory is intentional and if we do what is proposed above then we will break how kustomize has been set up. How the three layers are organized is explained here:

https://github.com/openstack-k8s-operators/architecture/pull/72

**Comment by fultonj** [comment]
To understand better, try this process.

1. clone this repo
2. install the kustomize binary (you don't need k8s installed to understand the structure, you just need to run the kustomize command)
3. run `kustomize build examples/common/olm/` and `kustomize build architecture/examples/va/hci` and examine the output CRs

If you want to dig deeper to interactively see how examples references the directories above it see https://github.com/openstack-k8s-operators/architecture/blob/main/docs/wa/missing_nncp.md#alternative-approach to understand
